### ISSUE TITLE
can you add feature close with keyboard?

### ISSUE THREAD

**Issue by arezascarlet** [marcelbohland/JavaScriptGallery#1]
please add feature to close image viewer with keyboard like key Esc, please

**Comment by marcelbohland** [comment]
Feature added in version 0.1.6. 

For use:
`enableKeydownESC();`

For self-implementation/other keys:
`$(document).keydown(function(e) {
    // ESCAPE key pressed
    if (e.keyCode == 27) {
        closeViewer();
    }
});`

**Comment by arezascarlet** [comment]
thank you 😊
